/** @type {import('tailwindcss').Config} */
// SonicCube v0.1.0 - 디자인 토큰: 프로토타입 (1. prototype design / Emerald & Gold)
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed-variant': '#454652',
        'inverse-primary': '#062c2b',
        'surface-container': '#0b3d3c',
        'secondary-container': '#10b981',
        'surface-variant': '#0d4341',
        'on-secondary-fixed-variant': '#064e3b',
        'surface-dim': '#041e1d',
        secondary: '#10b981',
        'secondary-fixed-dim': '#10b981',
        'on-primary-fixed': '#2d2000',
        'on-tertiary-fixed': '#1a1b26',
        'on-primary-fixed-variant': '#5a4500',
        'on-secondary-fixed': '#022c22',
        'surface-bright': '#0e5a58',
        background: '#062c2b',
        'primary-fixed': '#fde68a',
        'on-surface': '#e2f3f1',
        'surface-container-highest': '#135451',
        tertiary: '#f9f6ff',
        'on-tertiary': '#2f303b',
        'on-surface-variant': '#94b1af',
        'tertiary-fixed-dim': '#c6c5d4',
        'on-error-container': '#ffdad6',
        'secondary-fixed': '#d1fae5',
        'on-background': '#e2f3f1',
        outline: '#6d8c8a',
        'on-secondary-container': '#022c22',
        'error-container': '#93000a',
        surface: '#062c2b',
        'outline-variant': '#2a5755',
        'surface-container-lowest': '#031716',
        'inverse-on-surface': '#031716',
        'inverse-surface': '#e2f3f1',
        'tertiary-container': '#dad9e9',
        error: '#ffb4ab',
        'on-secondary': '#ffffff',
        'primary-container': '#fbbf24',
        primary: '#fbbf24',
        'on-error': '#690005',
        'surface-container-low': '#083332',
        'on-primary': '#453300',
        'surface-tint': '#fbbf24',
        'tertiary-fixed': '#e2e1f1',
        'on-tertiary-container': '#5e5e6c',
        'primary-fixed-dim': '#fbbf24',
        'on-primary-container': '#453300',
        'surface-container-high': '#0e4b48',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'margin-mobile': '16px',
        'margin-desktop': '32px',
        gutter: '16px',
        unit: '4px',
        'panel-gap': '1px',
      },
      fontFamily: {
        'headline-lg': ['Moirai One', 'Geist', 'sans-serif'],
        'headline-md': ['Moirai One', 'Geist', 'sans-serif'],
        'body-lg': ['Geist', 'sans-serif'],
        'body-md': ['Geist', 'sans-serif'],
        'label-mono-lg': ['JetBrains Mono', 'monospace'],
        'label-mono-sm': ['JetBrains Mono', 'monospace'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'label-mono-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '500' }],
        'headline-lg': ['30px', { lineHeight: '40px', letterSpacing: '0em', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '0em', fontWeight: '400' }],
        'label-mono-sm': ['11px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
